### ISSUE TITLE
Style Layer testing variant 

### ISSUE THREAD

**Issue by ProGamerGov** [bododge/neural-style-gradient#2]
```
for scc in `seq 1 12`;
do 
stylescale=$(echo "scale=2;$stylescale -.1" | bc)
tvweight=$(echo "scale=5;$tvweight +.00004" | bc) 

#This step creates seven style gradient steps for each of the loops above, adjusting only styleweight and contentweight. Change the gradient steps by adjusting the values below.

for q in `seq 1 12`;
do 
thisrun="sc$scc$sep$stylescale" 
styleweight=$((styleweight+900))
contentweight=$((contentweight-5))

```

I am unfamiliar with the language but I am trying to make it do 12 style layers and 12 content layers in order to help determine the best layers for an image.

**Comment by bododge** [comment]
I don't think you can process more than 5 layers with jc's script as-is. Maybe I'm wrong but I remember getting errors when I tried.

If you were adjusting the content layers and style layers you'd be trying to effect these variables
contentlayers="relu0,relu3,relu7,relu12"
stylelayers="relu0,relu3,relu7,relu12"

I might create something for this in the future, but I'm unsure of how you'd want to step through them as opposed to the other variables for styleweight and content weight.
